attack_lstm:
	python3 discrete_attack.py 2 2 LSTM ../data/train.tsv ../data/test.tsv ../data/changed_lstm --embedding_path c.txt --model_path ../model/model_lstm.pt 20000 FAKE

attack_cnn:
	python3 discrete_attack.py 2 2 CNN ../data/train.tsv ../data/test.tsv ../data/changed_cnn_train --embedding_path c.txt  --model_path ../model/model_cnn.pt 20000 FAKE

